---
abstract: 'EXPERIMENTAL - define multiple packages in one file, and reference them in any order'
author:
  - 'Karen Etheridge <ether@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::CheckDeps: 0.002
  Test::More: 0.88
  Test::Warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: me-inlined
no_index:
  directory:
    - t
    - xt
    - examples
provides:
  me::inlined:
    file: lib/me/inlined.pm
    version: 0.001
requires:
  Module::Runtime: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=me-inlined
  homepage: https://github.com/karenetheridge/me-inlined
  repository: https://github.com/karenetheridge/me-inlined.git
version: 0.001
x_Dist_Zilla:
  perl:
    version: 5.016003
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::ETHER/Git::NextVersion'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::ETHER/GithubMeta'
      version: 0.28
    -
      class: Dist::Zilla::Plugin::AutoMetaResources
      name: '@Author::ETHER/AutoMetaResources'
      version: 1.110050
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::ETHER/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Author::ETHER/MetaNoIndex'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Author::ETHER/MetaProvides::Package'
      version: 1.14000002
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::ETHER/MetaConfig'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::ETHER/ExecDir'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::ETHER/ShareDir'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Author::ETHER/Git::GatherDir'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::ETHER/MetaYAML'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::ETHER/MetaJSON'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::ETHER/License'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::ETHER/Readme'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::ETHER/Manifest'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@Author::ETHER/Test::Compile'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::Test::CheckDeps
      name: '@Author::ETHER/Test::CheckDeps'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@Author::ETHER/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Author::ETHER/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::ETHER/MetaTests'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: '@Author::ETHER/Test::Version'
      version: 0.002004
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::ETHER/Test::CPAN::Changes'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Test::ChangesHasContent
      name: '@Author::ETHER/Test::ChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::ETHER/Test::MinimumVersion'
      version: 2.000003
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::ETHER/PodSyntaxTests'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::ETHER/PodCoverageTests'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      name: '@Author::ETHER/Test::PodSpelling'
      version: 2.004003
    -
      class: Dist::Zilla::Plugin::Test::Pod::No404s
      name: '@Author::ETHER/Test::Pod::No404s'
      version: 1.001
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::ETHER/PruneCruft'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::ETHER/ManifestSkip'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: '@Author::ETHER/Git::Describe'
      version: 0.002
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::ETHER/PkgVersion'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Author::ETHER/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::ETHER/NextRelease'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::ETHER/AutoPrereqs'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::ETHER/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::ETHER/ReadmeAnyFromPod'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::ETHER/MakeMaker'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Author::ETHER/InstallGuide'
      version: 1.200000
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@Author::ETHER/CopyFilesFromBuild'
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: '@Author::ETHER/RunExtraTests'
      version: 0.011
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::ETHER/Git::Check'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::MergeConflicts
      name: '@Author::ETHER/Git::CheckFor::MergeConflicts'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@Author::ETHER/Git::CheckFor::CorrectBranch'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::Remote::Check
      name: '@Author::ETHER/Git::Remote::Check'
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Author::ETHER/CheckPrereqsIndexed'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::ETHER/TestRelease'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::ETHER/UploadToCPAN'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::ETHER/Git::Commit'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::ETHER/Git::Tag'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::ETHER/Git::Push'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::ETHER/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::ETHER/ConfirmRelease'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      name: Test::Kwalitee
      version: 2.03
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300034
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300034
x_authority: cpan:ETHER
